ping fw-caw.caw.local
ping docker-caw.caw.local
ping dhcp1-caw.caw.local
ping dhcp2-caw.caw.local
ping dc1-caw.caw.local
ping dc2-caw.caw.local
ping mgmt1-caw.caw.local
ping mgmt2-caw.caw.local
ping dfs1-caw.caw.local
ping dfs2-caw.caw.local
ping w1-caw.caw.local
ping w2-caw.caw.local
ping util-caw.caw.local
