Test-Connection -Count 1 champlain.edu
Test-Connection -Count 1 fw-caw.caw.local
Test-Connection -Count 1 docker-caw.caw.local
Test-Connection -Count 1 dhcp1-caw.caw.local
Test-Connection -Count 1 dhcp2-caw.caw.local
Test-Connection -Count 1 dc1-caw.caw.local
Test-Connection -Count 1 dc2-caw.caw.local
Test-Connection -Count 1 mgmt1-caw.caw.local
Test-Connection -Count 1 mgmt2-caw.caw.local
Test-Connection -Count 1 dfs1-caw.caw.local
Test-Connection -Count 1 dfs2-caw.caw.local
Test-Connection -Count 1 w1-caw.caw.local
Test-Connection -Count 1 w2-caw.caw.local
Test-Connection -Count 1 util-caw.caw.local
