- name: Deploy Nextcloud on util-caw
  hosts: util-caw
  become: yes
  
  tasks:
    - name: Install Apache, MariaDB, PHP and dependencies
      command: dnf install -y httpd mariadb-server php php-gd php-mbstring php-intl php-mysqlnd php-opcache php-xml php-zip wget unzip
      args:
        warn: no
        
    - name: Start and enable MariaDB
      command: "{{ item }}"
      with_items:
        - systemctl start mariadb
        - systemctl enable mariadb
      args:
        warn: no
        
    - name: Start and enable Apache
      command: "{{ item }}"
      with_items:
        - systemctl start httpd
        - systemctl enable httpd
      args:
        warn: no
        
    - name: Create Nextcloud database
      command: "{{ item }}"
      with_items:
        - mysql -e "CREATE DATABASE IF NOT EXISTS nextcloud CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;"
        - mysql -e "CREATE USER IF NOT EXISTS 'nextcloud'@'localhost' IDENTIFIED BY 'password';"
        - mysql -e "GRANT ALL PRIVILEGES ON nextcloud.* TO 'nextcloud'@'localhost';"
        - mysql -e "FLUSH PRIVILEGES;"
      args:
        warn: no
        
    - name: Create Nextcloud data directory
      command: mkdir -p /var/nc-data
      args:
        creates: /var/nc-data
        warn: no
        
    - name: Set permissions on data directory
      command: chown apache:apache /var/nc-data
      args:
        warn: no
        
    - name: Download Nextcloud
      command: wget -q https://download.nextcloud.com/server/releases/latest.zip -O /tmp/nextcloud.zip
      args:
        creates: /tmp/nextcloud.zip
        warn: no
        
    - name: Extract Nextcloud
      command: unzip -q /tmp/nextcloud.zip -d /var/www/html/
      args:
        creates: /var/www/html/nextcloud
        warn: no
        
    - name: Set ownership for Nextcloud
      command: chown -R apache:apache /var/www/html/nextcloud/
      args:
        warn: no
        
    - name: Create Apache configuration for Nextcloud
      copy:
        dest: /etc/httpd/conf.d/nextcloud.conf
        content: |
          Alias /nextcloud "/var/www/html/nextcloud/"

          <Directory /var/www/html/nextcloud/>
            Options +FollowSymlinks
            AllowOverride All
            Require all granted
          </Directory>
          
    - name: Restart Apache
      command: systemctl restart httpd
      args:
        warn: no
        
    - name: Open firewall for HTTP
      command: "{{ item }}"
      with_items:
        - firewall-cmd --permanent --add-service=http
        - firewall-cmd --reload
      args:
        warn: no
      ignore_errors: yes
      
    - name: Show completion message
      debug:
        msg: |
          Nextcloud files have been installed to /var/www/html/nextcloud
          
          To complete setup, open http://your-server-ip/nextcloud in your browser
          
          Use the following details for database setup:
            Database: MySQL/MariaDB
            Database name: nextcloud
            Database user: nextcloud
            Database password: password
            Database host: localhost
